---
apiVersion: v2
name: openobserve
description: An umbrella helm chart for OpenObserve log storage with a Fluent Bit collector
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: openobserve-standalone
    version: 0.80.3
    repository: https://charts.openobserve.ai
  - name: fluent-bit
    version: 0.57.8
    repository: https://fluent.github.io/helm-charts
