---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dinglink-ingress-certificate
spec:
  secretName: dinglink-ingress-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - dinglink.cluster.simonjung.io
