---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: longhorn-ingress-certificate
spec:
    secretName: longhorn-ingress-secret
    issuerRef:
        name: cloudflare-clusterissuer
        kind: ClusterIssuer
    dnsNames:
        - longhorn.cluster.simonjung.io
