---
apiVersion: v1
kind: Service
metadata:
  name: plex
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      name: web-interface
      port: 32400
      targetPort: 32400
  selector:
    app: plex
