---
apiVersion: v1
kind: Service
metadata:
  name: plex
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: web-interface
      port: 32400
      nodePort: 32400
  selector:
    app: plex
