---
traefik:
  ports:
    web:
      http:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
    websecure:
      http:
        tls:
          enabled: true
  ingressRoute:
    dashboard:
      enabled: true
      entryPoints: [web, websecure]
      matchRule: Host(`traefik.cluster.simonjung.io`)
      tls:
        secretName: traefik-ingress-secret
certificate:
  secretName: traefik-ingress-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
