---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-pvc
spec:
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
