---
apiVersion: v1
kind: Service
metadata:
  name: transmission
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 9091
      protocol: TCP
      name: http
  selector:
    app: transmission
