apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-development
  namespace: argocd
spec:
  destination:
    namespace: redis-development
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: redis
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 23.1.1
      helm:
        valueFiles:
        - $values/apps/redis/envs/development/values.yaml
    - repoURL: git@github.com:simonyjung/k3s-homelab.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true