---
apiVersion: v2
name: montioring
description: An Umbrella helm chart for monitoring using prometheus and grafana
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: kube-prometheus-stack
    version: 80.14.4
    repository: https://prometheus-community.github.io/helm-charts
