---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: linkding-ingress-certificate
spec:
    secretName: linkding-ingress-certificate
    issuerRef:
        name: cloudflare-clusterissuer
        kind: ClusterIssuer
    dnsNames:
    - linkding.cluster.simonjung.io