apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
  annotations:
    kubernetes.io/service-account.name: homepage