---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: grafana-ingress-certificate
spec:
    secretName: grafana-ingress-secret
    issuerRef:
        name: cloudflare-clusterissuer
        kind: ClusterIssuer
    dnsNames:
        - grafana.cluster.simonjung.io
