apiVersion: v1
kind: Service
metadata:
  name: linkding
  namespace: linkding
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      containerPort: 9090
  selector:
    app: linkding