apiVersion: v1
kind: Service
metadata:
  name: linkding
  namespace: linkding
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 32169
      targetPort: 9090
      protocol: TCP
  selector:
    app: linkding