---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{.Values.clusterIssuer.name}}
spec:
  acme:
    email: {{.Values.clusterIssuer.acme.email}}
    server: {{.Values.clusterIssuer.acme.server | default "https://acme-v02.api.letsencrypt.org/directory"}}
    privateKeySecretRef:
      name: {{.Values.clusterIssuer.acme.privateKeySecretRefName}}
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: {{.Values.cloudflare.secretName}}
              key: {{.Values.cloudflare.key}}
