---
apiVersion: v2
name: metallb
description: An Umbrella helm chart for metallb
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: metallb
    version: 0.15.2
    repository: https://metallb.github.io/metallb
