---
apiVersion: v2
name: open-webui
description: An Umbrella helm chart for openwebui
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: open-webui
    version: 10.2.1
    repository: https://helm.openwebui.com
