---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: homepage-ingress-certificate
spec:
    secretName: homepage-ingress-secret
    issuerRef:
        name: cloudflare-clusterissuer
        kind: ClusterIssuer
    dnsNames:
    - homepage.cluster.simonjung.io