---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml
  - certificate.yaml
  - onepasswordsecret.yaml
  - cloudflared.yaml

patchesStrategicMerge:
  - clusterrolebinding.yaml

configMapGenerator:
  - name: homepage
    files:
      - config/bookmarks.yaml
      - config/custom.css
      - config/custom.js
      - config/docker.yaml
      - config/kubernetes.yaml
      - config/services.yaml
      - config/settings.yaml
      - config/widgets.yaml
