apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-production
  namespace: argocd
spec:
  destination:
    namespace: hello-world-production
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: nginx
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 22.0.10
      helm:
        valueFiles:
        - $values/apps/helmapp/envs/production/values.yaml
    - repoURL: git@github.com:simonyjung/k3s-homelab.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true