---
apiVersion: v2
name: cloudnative-pg
description: An Umbrella helm chart for the CloudNativePG Postgres operator
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: cloudnative-pg
    version: 0.29.0
    repository: https://cloudnative-pg.github.io/charts
