---
apiVersion: v2
name: grafana
description: An Umbrella helm chart for grafana
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: grafana
    version: 10.1.2
    repository: https://grafana.github.io/helm-charts
